<?php
/**
 * This file contains code to implement the class DieGraphic.
 * @author Jenny Rigsjö (anri16)
 * @version 1.0.0
 */

namespace Anri16\Dice100;

/**
 * A supporting class for the game 'Dice 100'.
 */
class DieGraphic extends Die1
{
    /**
     * Constructor to initiate a single die.
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * Get a graphic representation of the value generated by rolling the die.
     *
     * @return string as a class name representing the graphic version of the value.
     */
    public function graphic()
    {
        $value = $this->getLastRoll();
        $className = "die-" . $value;
        return $className;
    }
}
